apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apiserver
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apiserver
    spec:
      containers:
      - image: brainupgrade/sba-apiserver:1.0.0
        name: sba-apiserver
        env:
        - name: spring.datasource.url
          value: "jdbc:postgresql://postgres:5432/app"
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 5
          successThreshold: 1
          periodSeconds: 10
          initialDelaySeconds: 9
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 1
status: {}