apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apiserver
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apiserver
    spec:
      affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - frontend
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: apiserver
      containers:
      - image: cielszx/sba:v2
        name: sba-apiserver
        env:
        - name: spring.datasource.url
          value: "jdbc:postgresql://postgres:5432/app"
status: {}