apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: brainupgrade/sba-frontend:base
        name: sba-frontend
        Environment:
          REACT_APP_API_URL:  https://scbcepb3u8-app.brainupgrade.net/api/
        resources: {}
status: {}