apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebook
      release: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: facebook
        release: v1
    spec:
      containers:
      - image: cielszx/sba-frontend:v3
        name: sba-frontend
        env:
        - name: REACT_APP_API_URL
          value: "https://scbcepb3u8-app.brainupgrade.net/api/"
status: {}